/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.perfumeria.vista.producto;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author coffeshell
 */
public class IFrameActualizarStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrameActualizarStock
     */
    public IFrameActualizarStock() {
        initComponents();
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JLabel getCantidadActual() {
        return cantidadActual;
    }

    public void setCantidadActual(JLabel cantidadActual) {
        this.cantidadActual = cantidadActual;
    }

    public JLabel getCantidadActualLabel() {
        return cantidadActualLabel;
    }

    public void setCantidadActualLabel(JLabel cantidadActualLabel) {
        this.cantidadActualLabel = cantidadActualLabel;
    }

    public JTextField getLotesAgregados() {
        return lotesAgregados;
    }

    public void setLotesAgregados(JTextField lotesAgregados) {
        this.lotesAgregados = lotesAgregados;
    }

    public JLabel getLotesAgregadosLabel() {
        return lotesAgregadosLabel;
    }

    public void setLotesAgregadosLabel(JLabel lotesAgregadosLabel) {
        this.lotesAgregadosLabel = lotesAgregadosLabel;
    }

    public JPanel getPorCantidadEspecifica() {
        return porCantidadEspecifica;
    }

    public void setPorCantidadEspecifica(JPanel porCantidadEspecifica) {
        this.porCantidadEspecifica = porCantidadEspecifica;
    }

    public JPanel getPorLotePane() {
        return porLotePane;
    }

    public void setPorLotePane(JPanel porLotePane) {
        this.porLotePane = porLotePane;
    }

    public JComboBox<String> getTipoActualzacion() {
        return tipoActualzacion;
    }

    public void setTipoActualzacion(JComboBox<String> tipoActualzacion) {
        this.tipoActualzacion = tipoActualzacion;
    }

    public JLabel getTipoActualzacionLabel() {
        return tipoActualzacionLabel;
    }

    public void setTipoActualzacionLabel(JLabel tipoActualzacionLabel) {
        this.tipoActualzacionLabel = tipoActualzacionLabel;
    }

    public JLabel getTituloLabel() {
        return tituloLabel;
    }

    public void setTituloLabel(JLabel tituloLabel) {
        this.tituloLabel = tituloLabel;
    }

    public JTextField getUnidadesAgregadas() {
        return unidadesAgregadas;
    }

    public void setUnidadesAgregadas(JTextField unidadesAgregadas) {
        this.unidadesAgregadas = unidadesAgregadas;
    }

    public JLabel getUnidadesAgregadasLabel() {
        return unidadesAgregadasLabel;
    }

    public void setUnidadesAgregadasLabel(JLabel unidadesAgregadasLabel) {
        this.unidadesAgregadasLabel = unidadesAgregadasLabel;
    }

    public JLabel getUnidadesPorLote() {
        return unidadesPorLote;
    }

    public void setUnidadesPorLote(JLabel unidadesPorLote) {
        this.unidadesPorLote = unidadesPorLote;
    }

    public JLabel getUnidadesPorLoteLabel() {
        return unidadesPorLoteLabel;
    }

    public void setUnidadesPorLoteLabel(JLabel unidadesPorLoteLabel) {
        this.unidadesPorLoteLabel = unidadesPorLoteLabel;
    }

  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        tipoActualzacionLabel = new javax.swing.JLabel();
        tipoActualzacion = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        porLotePane = new javax.swing.JPanel();
        unidadesPorLoteLabel = new javax.swing.JLabel();
        unidadesPorLote = new javax.swing.JLabel();
        lotesAgregadosLabel = new javax.swing.JLabel();
        lotesAgregados = new javax.swing.JTextField();
        porCantidadEspecifica = new javax.swing.JPanel();
        unidadesAgregadasLabel = new javax.swing.JLabel();
        unidadesAgregadas = new javax.swing.JTextField();
        cantidadActualLabel = new javax.swing.JLabel();
        cantidadActual = new javax.swing.JLabel();

        setClosable(true);

        tituloLabel.setFont(new java.awt.Font("JetBrains Mono", 2, 24)); // NOI18N
        tituloLabel.setText("Actualizar stock de producto");

        tipoActualzacionLabel.setText("tipo de actualizacion");

        tipoActualzacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Lote", "Cantidad Específica" }));

        btnActualizar.setText("Actualizar");

        unidadesPorLoteLabel.setText("Unidades Por lote:");

        unidadesPorLote.setText("0");

        lotesAgregadosLabel.setText("lotes agregados: ");

        lotesAgregados.setText("0");
        lotesAgregados.setToolTipText("");
        lotesAgregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotesAgregadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout porLotePaneLayout = new javax.swing.GroupLayout(porLotePane);
        porLotePane.setLayout(porLotePaneLayout);
        porLotePaneLayout.setHorizontalGroup(
            porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porLotePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadesPorLoteLabel)
                    .addComponent(lotesAgregadosLabel))
                .addGap(29, 29, 29)
                .addGroup(porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadesPorLote)
                    .addComponent(lotesAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        porLotePaneLayout.setVerticalGroup(
            porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porLotePaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadesPorLoteLabel)
                    .addComponent(unidadesPorLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(porLotePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotesAgregadosLabel)
                    .addComponent(lotesAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        unidadesAgregadasLabel.setText("Unidades Agregadas: ");

        unidadesAgregadas.setText("0");

        javax.swing.GroupLayout porCantidadEspecificaLayout = new javax.swing.GroupLayout(porCantidadEspecifica);
        porCantidadEspecifica.setLayout(porCantidadEspecificaLayout);
        porCantidadEspecificaLayout.setHorizontalGroup(
            porCantidadEspecificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porCantidadEspecificaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unidadesAgregadasLabel)
                .addGap(18, 18, 18)
                .addComponent(unidadesAgregadas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );
        porCantidadEspecificaLayout.setVerticalGroup(
            porCantidadEspecificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porCantidadEspecificaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(porCantidadEspecificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadesAgregadasLabel)
                    .addComponent(unidadesAgregadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        cantidadActualLabel.setText("Cantidad Actual: ");

        cantidadActual.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porCantidadEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porLotePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoActualzacionLabel)
                        .addGap(45, 45, 45)
                        .addComponent(tipoActualzacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(cantidadActualLabel)
                        .addGap(36, 36, 36)
                        .addComponent(cantidadActual))
                    .addComponent(tituloLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoActualzacionLabel)
                            .addComponent(tipoActualzacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadActualLabel)
                            .addComponent(cantidadActual))))
                .addGap(18, 18, 18)
                .addComponent(porLotePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porCantidadEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotesAgregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotesAgregadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotesAgregadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel cantidadActual;
    private javax.swing.JLabel cantidadActualLabel;
    private javax.swing.JTextField lotesAgregados;
    private javax.swing.JLabel lotesAgregadosLabel;
    private javax.swing.JPanel porCantidadEspecifica;
    private javax.swing.JPanel porLotePane;
    private javax.swing.JComboBox<String> tipoActualzacion;
    private javax.swing.JLabel tipoActualzacionLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField unidadesAgregadas;
    private javax.swing.JLabel unidadesAgregadasLabel;
    private javax.swing.JLabel unidadesPorLote;
    private javax.swing.JLabel unidadesPorLoteLabel;
    // End of variables declaration//GEN-END:variables
}
